import tkinter as tk

import pytest

from gui import ExpenseDialog, SettlementDialog, _decode_group_qr, _encode_group_qr, _u


@pytest.fixture
def root():
    r = tk.Tk()
    r.withdraw()
    yield r
    r.destroy()


USERS = [
    {"public_key": "alice", "name": "Alice"},
    {"public_key": "bob", "name": "Bob"},
]


def _current_dialog(root) -> ExpenseDialog:
    tops = [w for w in root.winfo_children() if isinstance(w, tk.Toplevel)]
    assert tops, "ExpenseDialog window not found under root"
    return tops[-1]  # type: ignore[return-value]


def _open_and_save(root, act) -> dict:
    """
    Opens an ExpenseDialog, runs `act(dlg)` to fill it in and save, then
    returns dlg.result. ExpenseDialog.__init__ blocks in wait_window(), so
    `act` is scheduled via root.after() and runs once the dialog exists.
    """
    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        act(dlg)
        holder["result"] = dlg.result

    root.after(50, run_act)
    ExpenseDialog(root, USERS, "alice", "EUR", {})
    return holder["result"]


def test_u_helper_normalizes_dict_and_object():
    assert _u({"public_key": "pk1", "name": "Alice"}) == ("pk1", "Alice")

    class FakeUser:
        public_key = "pk2"
        name = "Bob"

    assert _u(FakeUser()) == ("pk2", "Bob")


def test_group_qr_encode_decode_roundtrip():
    """Regression: decode used to check for v1/pw/salt while encode produces
    v3/key/topic, so a QR generated by this app could never be scanned by it."""
    group_key = b"0" * 32
    payload = _encode_group_qr("Islandtrip", group_key, "topic-uuid", "EUR")
    result = _decode_group_qr(payload)
    assert result["name"] == "Islandtrip"
    assert result["key"] == group_key.hex()
    assert result["topic"] == "topic-uuid"
    assert result["currency"] == "EUR"


def test_group_qr_decode_rejects_unknown_version():
    with pytest.raises(ValueError):
        _decode_group_qr('{"v": 1, "name": "x", "pw": "y", "salt": "00", "currency": "EUR"}')


def test_expense_dialog_equal_split(root):
    def act(dlg):
        dlg._desc.set("Dinner")
        dlg._amount.set("100")
        dlg._split_mode.set("equal")
        dlg._save()

    result = _open_and_save(root, act)
    assert result["description"] == "Dinner"
    assert result["split_mode"] == "equal"
    assert set(result["debtor_keys"]) == {"alice", "bob"}
    assert result["split_percentages"] is None
    assert result["split_custom_amounts"] is None


def test_expense_dialog_amount_is_converted_to_minor_units(root):
    """Regression: to_minor() was never called anywhere in gui.py, so a
    100.00 EUR expense was stored as amount=100 instead of amount=10000,
    making every displayed amount wrong by a factor of 100."""

    def act(dlg):
        dlg._desc.set("Dinner")
        dlg._amount.set("12.50")
        dlg._save()

    result = _open_and_save(root, act)
    assert result["amount"] == 1250


def test_expense_dialog_edit_prefill_shows_major_units(root):
    """Editing an existing expense must show 12.50, not the raw minor-unit 1250."""
    from models import Expense

    exp = Expense.create(group_id="g1", description="Dinner", amount=1250, author_pubkey="alice")

    def act(dlg):
        assert dlg._amount.get() == "12.5"
        dlg._save()

    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        act(dlg)
        holder["result"] = dlg.result

    root.after(50, run_act)
    ExpenseDialog(root, USERS, "alice", "EUR", {}, exp)
    assert holder["result"]["amount"] == 1250


def test_expense_dialog_percent_split_result(root):
    def act(dlg):
        dlg._desc.set("Rent")
        dlg._amount.set("100")
        dlg._split_mode.set("percent")
        dlg._percent_vars["alice"].set("70")
        dlg._percent_vars["bob"].set("30")
        dlg._save()

    result = _open_and_save(root, act)
    assert result["split_mode"] == "percent"
    assert result["split_percentages"] == {"alice": 70.0, "bob": 30.0}
    assert result["split_custom_amounts"] is None


def test_expense_dialog_custom_split_result(root):
    def act(dlg):
        dlg._desc.set("Groceries")
        dlg._amount.set("100")
        dlg._split_mode.set("custom")
        dlg._amount_vars["alice"].set("40")
        dlg._amount_vars["bob"].set("60")
        dlg._save()

    result = _open_and_save(root, act)
    assert result["split_mode"] == "custom"
    # Amounts are converted to minor units (cents) before being stored.
    assert result["split_custom_amounts"] == {"alice": 4000, "bob": 6000}
    assert result["split_percentages"] is None


def test_expense_dialog_only_selected_members_become_debtor_keys(root):
    def act(dlg):
        dlg._desc.set("Solo snack")
        dlg._amount.set("10")
        dlg._split_mode.set("equal")
        dlg._member_vars["bob"].set(False)  # deselect Bob
        dlg._save()

    result = _open_and_save(root, act)
    assert result["debtor_keys"] == ["alice"]


def test_build_splits_dispatches_by_mode(root):
    """App._build_splits must route to the split fn matching split_mode
    (regression for the bug where it always used split_equally)."""
    from gui import App

    app = App.__new__(App)  # bypass __init__ (no DB/network needed for this)

    equal = app._build_splits(
        "exp1",
        100,
        "alice",
        ["alice", "bob"],
        {"split_mode": "equal"},
    )
    assert sorted(s.amount for s in equal) == [50, 50]

    percent = app._build_splits(
        "exp1",
        100,
        "alice",
        ["alice", "bob"],
        {"split_mode": "percent", "split_percentages": {"alice": 70.0, "bob": 30.0}},
    )
    assert {s.debtor_key: s.amount for s in percent} == {"alice": 70, "bob": 30}

    custom = app._build_splits(
        "exp1",
        100,
        "alice",
        ["alice", "bob"],
        {"split_mode": "custom", "split_custom_amounts": {"alice": 10, "bob": 90}},
    )
    assert {s.debtor_key: s.amount for s in custom} == {"alice": 10, "bob": 90}


def test_settlement_dialog_amount_is_converted_to_minor_units(root):
    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        dlg._amount.set("50")
        dlg._save()
        holder["result"] = dlg.result

    root.after(50, run_act)
    SettlementDialog(root, USERS, "alice", "EUR", {})
    assert holder["result"]["amount"] == 5000


def test_settlement_dialog_prefill_shows_major_units(root):
    """The prefill amount (e.g. from a suggested settlement) arrives in minor
    units and must be shown to the user in major units."""
    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        assert dlg._amount.get() == "12.5"
        dlg._save()
        holder["result"] = dlg.result

    root.after(50, run_act)
    SettlementDialog(root, USERS, "alice", "EUR", {}, {"amount": 1250})
    assert holder["result"]["amount"] == 1250
