import tkinter as tk
from tkinter import ttk
from unittest.mock import patch

import pytest

from gui import (
    AddMemberDialog,
    ChartsWindow,
    ExpenseDialog,
    ExportDialog,
    GroupSelectDialog,
    NewGroupDialog,
    QRImportDialog,
    QRShowDialog,
    SettlementDialog,
    StorageSetupDialog,
    _decode_group_qr,
    _encode_group_qr,
    _u,
)


@pytest.fixture
def root():
    r = tk.Tk()
    r.withdraw()
    yield r
    r.destroy()


USERS = [
    {"public_key": "alice", "name": "Alice"},
    {"public_key": "bob", "name": "Bob"},
]


def _current_dialog(root) -> ExpenseDialog:
    tops = [w for w in root.winfo_children() if isinstance(w, tk.Toplevel)]
    assert tops, "ExpenseDialog window not found under root"
    return tops[-1]  # type: ignore[return-value]


def _open_and_save(root, act) -> dict:
    """
    Opens an ExpenseDialog, runs `act(dlg)` to fill it in and save, then
    returns dlg.result. ExpenseDialog.__init__ blocks in wait_window(), so
    `act` is scheduled via root.after() and runs once the dialog exists.
    """
    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        act(dlg)
        holder["result"] = dlg.result

    root.after(50, run_act)
    ExpenseDialog(root, USERS, "alice", "EUR", {})
    return holder["result"]


def test_u_helper_normalizes_dict_and_object():
    assert _u({"public_key": "pk1", "name": "Alice"}) == ("pk1", "Alice")

    class FakeUser:
        public_key = "pk2"
        name = "Bob"

    assert _u(FakeUser()) == ("pk2", "Bob")


def test_u_helper_normalizes_sqlite_row():
    """Regression: sqlite3.Row is neither a dict (isinstance check fails) nor
    does it support attribute access (getattr falls through to the ""/"?"
    defaults) — every real caller of _u() passes storage.get_all_users() rows,
    so this silently normalized every member to pubkey "" instead of raising,
    corrupting member lookups (wrong debtor keys, collapsed chart series)."""
    import storage

    db = storage.init_db(":memory:")
    storage.save_user(
        db,
        group_id="g1",
        public_key="pk1",
        name="Alice",
        timestamp=1,
        lamport_clock=1,
        signature="",
    )
    row = storage.get_all_users(db, "g1")[0]
    assert _u(row) == ("pk1", "Alice")


def test_group_qr_encode_decode_roundtrip():
    """Regression: decode used to check for v1/pw/salt while encode produces
    v3/key/topic, so a QR generated by this app could never be scanned by it."""
    group_key = b"0" * 32
    payload = _encode_group_qr("Islandtrip", group_key, "topic-uuid", "EUR")
    result = _decode_group_qr(payload)
    assert result["name"] == "Islandtrip"
    assert result["key"] == group_key.hex()
    assert result["topic"] == "topic-uuid"
    assert result["currency"] == "EUR"


def test_group_qr_decode_rejects_unknown_version():
    with pytest.raises(ValueError):
        _decode_group_qr('{"v": 1, "name": "x", "pw": "y", "salt": "00", "currency": "EUR"}')


def test_expense_dialog_equal_split(root):
    def act(dlg):
        dlg._desc.set("Dinner")
        dlg._amount.set("100")
        dlg._split_mode.set("equal")
        dlg._save()

    result = _open_and_save(root, act)
    assert result["description"] == "Dinner"
    assert result["split_mode"] == "equal"
    assert set(result["debtor_keys"]) == {"alice", "bob"}
    assert result["split_percentages"] is None
    assert result["split_custom_amounts"] is None


def test_expense_dialog_amount_is_converted_to_minor_units(root):
    """Regression: to_minor() was never called anywhere in gui.py, so a
    100.00 EUR expense was stored as amount=100 instead of amount=10000,
    making every displayed amount wrong by a factor of 100."""

    def act(dlg):
        dlg._desc.set("Dinner")
        dlg._amount.set("12.50")
        dlg._save()

    result = _open_and_save(root, act)
    assert result["amount"] == 1250


def test_expense_dialog_edit_prefill_shows_major_units(root):
    """Editing an existing expense must show 12.50, not the raw minor-unit 1250."""
    from models import Expense

    exp = Expense.create(group_id="g1", description="Dinner", amount=1250, author_pubkey="alice")

    def act(dlg):
        assert dlg._amount.get() == "12.5"
        dlg._save()

    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        act(dlg)
        holder["result"] = dlg.result

    root.after(50, run_act)
    ExpenseDialog(root, USERS, "alice", "EUR", {}, exp)
    assert holder["result"]["amount"] == 1250


def test_expense_dialog_percent_split_result(root):
    def act(dlg):
        dlg._desc.set("Rent")
        dlg._amount.set("100")
        dlg._split_mode.set("percent")
        dlg._percent_vars["alice"].set("70")
        dlg._percent_vars["bob"].set("30")
        dlg._save()

    result = _open_and_save(root, act)
    assert result["split_mode"] == "percent"
    assert result["split_percentages"] == {"alice": 70.0, "bob": 30.0}
    assert result["split_custom_amounts"] is None


def test_expense_dialog_custom_split_result(root):
    def act(dlg):
        dlg._desc.set("Groceries")
        dlg._amount.set("100")
        dlg._split_mode.set("custom")
        dlg._amount_vars["alice"].set("40")
        dlg._amount_vars["bob"].set("60")
        dlg._save()

    result = _open_and_save(root, act)
    assert result["split_mode"] == "custom"
    # Amounts are converted to minor units (cents) before being stored.
    assert result["split_custom_amounts"] == {"alice": 4000, "bob": 6000}
    assert result["split_percentages"] is None


def test_expense_dialog_only_selected_members_become_debtor_keys(root):
    def act(dlg):
        dlg._desc.set("Solo snack")
        dlg._amount.set("10")
        dlg._split_mode.set("equal")
        dlg._member_vars["bob"].set(False)  # deselect Bob
        dlg._save()

    result = _open_and_save(root, act)
    assert result["debtor_keys"] == ["alice"]


def test_build_splits_dispatches_by_mode(root):
    """App._build_splits must route to the split fn matching split_mode
    (regression for the bug where it always used split_equally)."""
    from gui import App

    app = App.__new__(App)  # bypass __init__ (no DB/network needed for this)

    equal = app._build_splits(
        "exp1",
        100,
        "alice",
        ["alice", "bob"],
        {"split_mode": "equal"},
    )
    assert sorted(s.amount for s in equal) == [50, 50]

    percent = app._build_splits(
        "exp1",
        100,
        "alice",
        ["alice", "bob"],
        {"split_mode": "percent", "split_percentages": {"alice": 70.0, "bob": 30.0}},
    )
    assert {s.debtor_key: s.amount for s in percent} == {"alice": 70, "bob": 30}

    custom = app._build_splits(
        "exp1",
        100,
        "alice",
        ["alice", "bob"],
        {"split_mode": "custom", "split_custom_amounts": {"alice": 10, "bob": 90}},
    )
    assert {s.debtor_key: s.amount for s in custom} == {"alice": 10, "bob": 90}


def test_settlement_dialog_amount_is_converted_to_minor_units(root):
    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        dlg._amount.set("50")
        dlg._save()
        holder["result"] = dlg.result

    root.after(50, run_act)
    SettlementDialog(root, USERS, "alice", "EUR", {})
    assert holder["result"]["amount"] == 5000


def test_settlement_dialog_prefill_shows_major_units(root):
    """The prefill amount (e.g. from a suggested settlement) arrives in minor
    units and must be shown to the user in major units."""
    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        assert dlg._amount.get() == "12.5"
        dlg._save()
        holder["result"] = dlg.result

    root.after(50, run_act)
    SettlementDialog(root, USERS, "alice", "EUR", {}, {"amount": 1250})
    assert holder["result"]["amount"] == 1250


def test_settlement_dialog_default_from_to_are_never_the_same(root):
    """Regression: default_to fell back to member_names[-1] unconditionally.
    When own_pubkey's name sorts alphabetically last (as it does here: "Zoe"
    > "Amy"), default_from and default_to both landed on "Zoe", so a user
    opening the dialog and hitting Save immediately got "From and To must be
    different" and the settlement was silently never saved."""
    users = [
        {"public_key": "amy", "name": "Amy"},
        {"public_key": "zoe", "name": "Zoe"},
    ]

    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        holder["from"] = dlg._from_var.get()
        holder["to"] = dlg._to_var.get()
        dlg.destroy()

    root.after(50, run_act)
    SettlementDialog(root, users, "zoe", "EUR", {})
    assert holder["from"] != holder["to"]


def test_export_dialog_csv_and_pdf(root, tmp_path):
    """Regression: ExportDialog referenced self._group_currency (never set,
    only self.currency) and expense.currency/settlement.currency (neither
    model has a currency field) — every export attempt raised AttributeError."""
    from models import Expense, Settlement, Split

    exp = Expense.create(
        group_id="g1",
        description="Dinner",
        amount=1250,
        author_pubkey="alice",
        category="Food & Drink",
    )
    exp.splits = [
        Split.create(
            belongs_to=exp.id,
            payer_key="alice",
            debtor_key="alice",
            amount=625,
            author_pubkey="alice",
        ),
        Split.create(
            belongs_to=exp.id,
            payer_key="alice",
            debtor_key="bob",
            amount=625,
            author_pubkey="alice",
        ),
    ]
    settlement = Settlement.create(
        group_id="g1",
        from_key="bob",
        to_key="alice",
        amount=625,
        author_pubkey="bob",
        note="thanks",
    )

    csv_path = tmp_path / "export.csv"
    pdf_path = tmp_path / "export.pdf"

    def run_export():
        dlg = _current_dialog(root)
        with (
            patch("tkinter.filedialog.asksaveasfilename", return_value=str(csv_path)),
            patch("gui.mb.showinfo"),
        ):
            dlg._export_csv()
        with (
            patch("tkinter.filedialog.asksaveasfilename", return_value=str(pdf_path)),
            patch("gui.mb.showinfo"),
        ):
            dlg._export_pdf()
        dlg.destroy()

    root.after(50, run_export)
    ExportDialog(root, [exp], [settlement], USERS, "EUR", "Islandtrip")

    csv_content = csv_path.read_text()
    assert "12.50" in csv_content  # exp.amount=1250 formatted as major units
    assert "6.25" in csv_content  # each split/settlement is 625 minor units
    assert pdf_path.exists() and pdf_path.stat().st_size > 0


def test_expense_dialog_edit_prefills_custom_split_and_participants(root):
    """Regression: the edit dialog used to always reset to split_mode='equal'
    with all members selected and blank custom-amount fields, discarding the
    expense's actual (unequal) split and its participant list."""
    from models import Expense, Split

    users_3 = [*USERS, {"public_key": "carol", "name": "Carol"}]
    exp = Expense.create(group_id="g1", description="Rent", amount=1000, author_pubkey="alice")
    exp.splits = [
        Split.create(
            belongs_to=exp.id,
            payer_key="alice",
            debtor_key="alice",
            amount=700,
            author_pubkey="alice",
        ),
        Split.create(
            belongs_to=exp.id,
            payer_key="alice",
            debtor_key="bob",
            amount=300,
            author_pubkey="alice",
        ),
    ]

    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        assert dlg._split_mode.get() == "custom"
        assert dlg._member_vars["alice"].get() is True
        assert dlg._member_vars["bob"].get() is True
        assert dlg._member_vars["carol"].get() is False  # not part of the original split
        assert dlg._amount_vars["alice"].get() == "7.0"
        assert dlg._amount_vars["bob"].get() == "3.0"
        dlg._save()
        holder["result"] = dlg.result

    root.after(50, run_act)
    ExpenseDialog(root, users_3, "alice", "EUR", {}, exp)
    result = holder["result"]
    assert result["split_mode"] == "custom"
    assert result["split_custom_amounts"] == {"alice": 700, "bob": 300}


def test_expense_dialog_edit_prefills_equal_split(root):
    from models import Expense, split_equally

    exp = Expense.create(group_id="g1", description="Dinner", amount=1000, author_pubkey="alice")
    exp.splits = split_equally(exp.id, exp.amount, "alice", ["alice", "bob"])

    def act(dlg):
        assert dlg._split_mode.get() == "equal"
        dlg._save()

    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        act(dlg)
        holder["result"] = dlg.result

    root.after(50, run_act)
    ExpenseDialog(root, USERS, "alice", "EUR", {}, exp)
    assert holder["result"]["split_mode"] == "equal"


def test_add_member_dialog_requires_name(root):
    """AddMemberDialog appears to be unreachable from the app UI (no call
    site instantiates it), but its own validation logic is worth locking in."""

    def act(dlg):
        with patch("gui.mb.showerror"):
            dlg._save()
        assert dlg.result is None  # empty name rejected, dialog stays open
        dlg._name_entry.insert(0, "Dave")
        dlg._pk.insert(0, "  ")  # blank pubkey -> None
        dlg._save()

    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        act(dlg)
        holder["result"] = dlg.result

    root.after(50, run_act)
    AddMemberDialog(root)
    assert holder["result"] == {"name": "Dave", "pubkey": None}


def test_storage_setup_dialog_creates_directories(root, tmp_path):
    db_path = tmp_path / "nested" / "splitp2p.db"
    att_dir = tmp_path / "attachments"

    def act(dlg):
        dlg._db_path.set(str(db_path))
        dlg._att_dir.set(str(att_dir))
        dlg._confirm()

    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        act(dlg)
        holder["result"] = dlg.result

    root.after(50, run_act)
    StorageSetupDialog(root, {"db_path": "", "storage_dir": ""})
    assert holder["result"] == {"db_path": str(db_path), "storage_dir": str(att_dir)}
    assert db_path.parent.exists()
    assert att_dir.exists()


def test_storage_setup_dialog_rejects_empty_paths(root):
    def act(dlg):
        dlg._db_path.set("")
        dlg._att_dir.set("")
        with patch("gui.mb.showerror"):
            dlg._confirm()
        assert dlg.result is None
        dlg.destroy()

    root.after(50, lambda: act(_current_dialog(root)))
    StorageSetupDialog(root, {"db_path": "", "storage_dir": ""})


def test_charts_window_renders_without_error(root):
    """ChartsWindow is not modal (no wait_window()), so it can be
    instantiated and inspected directly."""
    from models import Expense, Settlement, Split

    exp = Expense.create(
        group_id="g1",
        description="Dinner",
        amount=1000,
        author_pubkey="alice",
        category="Food & Drink",
    )
    exp.splits = [
        Split.create(
            belongs_to=exp.id,
            payer_key="alice",
            debtor_key="alice",
            amount=500,
            author_pubkey="alice",
        ),
        Split.create(
            belongs_to=exp.id,
            payer_key="alice",
            debtor_key="bob",
            amount=500,
            author_pubkey="alice",
        ),
    ]
    settlement = Settlement.create(
        group_id="g1", from_key="bob", to_key="alice", amount=500, author_pubkey="bob"
    )

    win = ChartsWindow(root, [exp], [settlement], USERS, "EUR", "alice")
    win.destroy()


def test_new_group_dialog_requires_name(root):
    def act(dlg):
        with patch("gui.mb.showerror"):
            dlg._confirm()
        assert dlg.result is None
        dlg._name_var.set("Islandtrip")
        dlg._confirm()

    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        act(dlg)
        holder["result"] = dlg.result

    root.after(50, run_act)
    NewGroupDialog(root)
    result = holder["result"]
    assert result["group_name"] == "Islandtrip"
    assert len(result["group_key"]) == 32
    assert result["group_currency"] == "EUR"
    import uuid

    uuid.UUID(result["group_topic"])  # raises ValueError if not a valid UUID


def test_group_select_dialog_no_groups_shows_create_and_import(root):
    def act(dlg):
        assert dlg.result is None
        dlg.destroy()

    root.after(50, lambda: act(_current_dialog(root)))
    GroupSelectDialog(root, {}, "")


def test_group_select_dialog_confirm_returns_selected_group(root):
    groups = {
        "Islandtrip": {"key": "00" * 32, "topic": "topic-1", "currency": "EUR"},
        "Roadtrip": {"key": "11" * 32, "topic": "topic-2", "currency": "USD"},
    }

    def act(dlg):
        dlg._selected.set("Roadtrip")
        dlg._confirm()

    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        act(dlg)
        holder["result"] = dlg.result

    root.after(50, run_act)
    GroupSelectDialog(root, groups, "Islandtrip")
    result = holder["result"]
    assert result["group_name"] == "Roadtrip"
    assert result["group_key"] == bytes.fromhex("11" * 32)
    assert result["group_currency"] == "USD"


def test_group_select_dialog_remove_group(root):
    groups = {"Islandtrip": {"key": "00" * 32, "topic": "t1", "currency": "EUR"}}

    def act(dlg):
        dlg._selected.set("Islandtrip")
        with patch("gui.mb.askyesno", return_value=True):
            dlg._remove_group()

    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        act(dlg)
        holder["result"] = dlg.result

    root.after(50, run_act)
    dlg_groups = dict(groups)
    GroupSelectDialog(root, dlg_groups, "Islandtrip")
    assert holder["result"] == {"_removed": "Islandtrip"}
    assert "Islandtrip" not in dlg_groups


def test_group_select_dialog_new_group_flow_sets_show_qr_after(root):
    """_new_group() must merge the freshly created group into self.groups
    and flag _show_qr_after so the App knows to display the QR code."""
    fake_new_group_result = {
        "group_name": "Islandtrip",
        "group_key": b"0" * 32,
        "group_topic": "topic-1",
        "group_currency": "EUR",
    }

    class FakeNewGroupDialog:
        def __init__(self, parent):
            self.result = fake_new_group_result

    def act(dlg):
        with patch("gui.NewGroupDialog", FakeNewGroupDialog):
            dlg._new_group()

    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        act(dlg)
        holder["result"] = dlg.result
        holder["show_qr_after"] = getattr(dlg, "_show_qr_after", False)
        holder["groups"] = groups

    root.after(50, run_act)
    groups: dict = {}
    GroupSelectDialog(root, groups, "")
    assert holder["result"] == fake_new_group_result
    assert holder["show_qr_after"] is True
    assert holder["groups"]["Islandtrip"]["key"] == (b"0" * 32).hex()


def test_group_select_dialog_import_qr_flow(root):
    fake_import_result = {
        "name": "Islandtrip",
        "key": "00" * 32,
        "topic": "topic-1",
        "currency": "EUR",
    }

    class FakeQRImportDialog:
        def __init__(self, parent):
            self.result = fake_import_result

    def act(dlg):
        with patch("gui.QRImportDialog", FakeQRImportDialog):
            dlg._import_qr()

    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        act(dlg)
        holder["result"] = dlg.result

    root.after(50, run_act)
    GroupSelectDialog(root, {}, "")
    result = holder["result"]
    assert result["group_name"] == "Islandtrip"
    assert result["group_key"] == bytes.fromhex("00" * 32)
    assert result["group_topic"] == "topic-1"


def test_qr_show_dialog_displays_payload_and_supports_copy(root):
    from gui import _encode_group_qr

    group_key = b"0" * 32
    expected_payload = _encode_group_qr("Islandtrip", group_key, "topic-1", "EUR")

    def act(dlg):
        assert dlg._payload == expected_payload
        dlg.clipboard_clear()
        dlg.clipboard_append(dlg._payload)
        assert dlg.clipboard_get() == expected_payload
        dlg.destroy()

    root.after(50, lambda: act(_current_dialog(root)))
    QRShowDialog(root, "Islandtrip", group_key, "topic-1", "EUR")


def test_qr_import_dialog_accepts_valid_code(root):
    group_key = b"0" * 32
    payload = _encode_group_qr("Islandtrip", group_key, "topic-1", "EUR")

    def act(dlg):
        dlg._text.insert("1.0", payload)
        dlg._import_text()
        assert dlg.result["name"] == "Islandtrip"
        assert dlg.result["key"] == group_key.hex()

    holder: dict = {}

    def run_act():
        dlg = _current_dialog(root)
        act(dlg)
        holder["result"] = dlg.result

    root.after(50, run_act)
    QRImportDialog(root)
    assert holder["result"]["name"] == "Islandtrip"


def test_qr_import_dialog_rejects_invalid_code(root):
    def act(dlg):
        dlg._text.insert("1.0", "not a valid qr code")
        dlg._import_text()
        assert dlg.result is None
        assert "Invalid" in dlg._status.cget("text")
        dlg.destroy()

    root.after(50, lambda: act(_current_dialog(root)))
    QRImportDialog(root)


def test_qr_import_dialog_empty_input_shows_status(root):
    def act(dlg):
        dlg._import_text()
        assert dlg.result is None
        assert "No code entered" in dlg._status.cget("text")
        dlg.destroy()

    root.after(50, lambda: act(_current_dialog(root)))
    QRImportDialog(root)


def _make_bare_app(root, db, group_id="g1", own_pubkey="alice"):
    """Builds an App instance bypassing __init__ (no real window, no
    identity/group-selection flow), with just enough real Tkinter widgets
    and state for _refresh()/_render_*() to run against a real DB."""
    from gui import App

    app = App.__new__(App)
    app._db = db
    app._group_id = group_id
    app._own_pubkey = own_pubkey
    app._group_currency = "EUR"
    app._network = None
    app._rates = {}
    app._pending_downloads = set()
    app._ledger_cache_key = None
    app._cached_balances = {}
    app._cached_debts = []
    app._log = []
    app._log_window = None
    app._search_text = tk.StringVar()
    app._filter_cat = tk.StringVar(value="All")
    app._filter_member = tk.StringVar(value="All")
    app._event_list = tk.Frame(root)
    app._member_filter_cb = ttk.Combobox(root)
    app._result_count = tk.Label(root)
    app._balance_frame = tk.Frame(root)
    app._debt_frame = tk.Frame(root)
    app._members_frame = tk.Frame(root)
    app._total_label = tk.Label(root)
    return app


def test_app_refresh_renders_expenses_and_settlements(root):
    """Integration test for the main events view. Regression: _render_expense_row
    referenced exp.attachment and exp.currency (neither exists on Expense —
    always AttributeError), and _render_settlement_row referenced
    s.original_amount/s.original_currency (didn't exist on Settlement either)
    — every single render of the main events list would crash."""
    import storage

    db = storage.init_db(":memory:")
    storage.save_user(
        db,
        group_id="g1",
        public_key="alice",
        name="Alice",
        timestamp=1,
        lamport_clock=1,
        signature="",
    )
    storage.save_user(
        db, group_id="g1", public_key="bob", name="Bob", timestamp=1, lamport_clock=1, signature=""
    )
    storage.save_expense(
        db,
        id="e1",
        group_id="g1",
        timestamp=100,
        expense_date=100,
        lamport_clock=1,
        author_pubkey="alice",
        amount=1000,
        description="Dinner",
        category="Food & Drink",
        signature="",
    )
    storage.save_splits(
        db,
        "e1",
        [
            {
                "id": "s1",
                "timestamp": 100,
                "lamport_clock": 1,
                "author_pubkey": "alice",
                "payer_key": "alice",
                "debtor_key": "alice",
                "amount": 500,
                "signature": "",
            },
            {
                "id": "s2",
                "timestamp": 100,
                "lamport_clock": 1,
                "author_pubkey": "alice",
                "payer_key": "alice",
                "debtor_key": "bob",
                "amount": 500,
                "signature": "",
            },
        ],
    )
    storage.save_settlement(
        db,
        id="st1",
        group_id="g1",
        timestamp=200,
        lamport_clock=1,
        author_pubkey="bob",
        from_key="bob",
        to_key="alice",
        amount=500,
        note="thanks",
        signature="",
    )

    app = _make_bare_app(root, db)
    app._refresh()

    assert len(app._event_list.winfo_children()) > 0
    assert "1 expenses" in app._total_label.cget("text")
    assert "1 payments" in app._total_label.cget("text")
    assert "10.00" in app._total_label.cget("text")


def test_app_refresh_with_attachment_does_not_crash(root, tmp_path):
    """Regression: exp.attachment didn't exist on the Expense model at all,
    so _render_expense_row raised AttributeError for every expense,
    attachment or not."""
    import storage

    storage.set_paths(":memory:", str(tmp_path))
    db = storage.init_db(":memory:")
    storage.save_user(
        db,
        group_id="g1",
        public_key="alice",
        name="Alice",
        timestamp=1,
        lamport_clock=1,
        signature="",
    )
    storage.save_expense(
        db,
        id="e1",
        group_id="g1",
        timestamp=100,
        expense_date=100,
        lamport_clock=1,
        author_pubkey="alice",
        amount=1000,
        description="Dinner",
        signature="",
    )
    storage.save_splits(
        db,
        "e1",
        [
            {
                "id": "s1",
                "timestamp": 100,
                "lamport_clock": 1,
                "author_pubkey": "alice",
                "payer_key": "alice",
                "debtor_key": "alice",
                "amount": 1000,
                "signature": "",
            }
        ],
    )
    storage.save_attachment(
        db,
        id="a1",
        belongs_to="e1",
        timestamp=100,
        lamport_clock=1,
        author_pubkey="alice",
        sha256="deadbeef",
        filename="receipt.png",
        mime="image/png",
        size=123,
        signature="",
    )
    storage.mark_attachment_stored(db, "deadbeef")
    (tmp_path / "deadbeef").write_bytes(b"fake image bytes")

    app = _make_bare_app(root, db)
    app._refresh()
    assert len(app._event_list.winfo_children()) > 0


def test_app_render_debts_shows_suggested_settlement(root):
    import storage

    db = storage.init_db(":memory:")
    storage.save_user(
        db,
        group_id="g1",
        public_key="alice",
        name="Alice",
        timestamp=1,
        lamport_clock=1,
        signature="",
    )
    storage.save_user(
        db, group_id="g1", public_key="bob", name="Bob", timestamp=1, lamport_clock=1, signature=""
    )
    storage.save_expense(
        db,
        id="e1",
        group_id="g1",
        timestamp=100,
        expense_date=100,
        lamport_clock=1,
        author_pubkey="alice",
        amount=1000,
        description="Dinner",
        signature="",
    )
    storage.save_splits(
        db,
        "e1",
        [
            {
                "id": "s1",
                "timestamp": 100,
                "lamport_clock": 1,
                "author_pubkey": "alice",
                "payer_key": "alice",
                "debtor_key": "alice",
                "amount": 500,
                "signature": "",
            },
            {
                "id": "s2",
                "timestamp": 100,
                "lamport_clock": 1,
                "author_pubkey": "alice",
                "payer_key": "alice",
                "debtor_key": "bob",
                "amount": 500,
                "signature": "",
            },
        ],
    )

    app = _make_bare_app(root, db)
    expenses = app._load_expenses()
    settlements = app._load_settlements()
    users = storage.get_all_users(db, "g1")
    app._render_debts(expenses, settlements, users)
    assert len(app._debt_frame.winfo_children()) > 0

    def all_label_texts(w):
        texts = []
        if isinstance(w, tk.Label):
            texts.append(w.cget("text"))
        for c in w.winfo_children():
            texts.extend(all_label_texts(c))
        return texts

    texts = all_label_texts(app._debt_frame)
    # Regression: _u() previously normalized every sqlite3.Row user to pubkey
    # "" (isinstance(dict) failed, getattr fell through), so pk_to_name mapped
    # nothing and names() fell back to the truncated raw pubkey everywhere.
    assert any("Bob" in t for t in texts)
    assert any("Alice" in t for t in texts)


def test_add_expense_with_new_attachment_round_trips(root, tmp_path):
    """Full write-path regression test: ExpenseDialog._save() used to call
    storage.save_attachment() with a completely wrong signature (2 positional
    args vs. the real (db, *, id, belongs_to, ...) kwargs) and construct
    Attachment(mime_type=...) (wrong kwarg name, missing required fields) —
    attaching any file to an expense crashed immediately. Verifies the whole
    create -> sign -> save -> mark_stored -> reload -> render path works."""
    import crypto
    import storage

    storage.set_paths(":memory:", str(tmp_path))
    db = storage.init_db(":memory:")
    storage.save_user(
        db,
        group_id="g1",
        public_key="alice",
        name="Alice",
        timestamp=1,
        lamport_clock=1,
        signature="",
    )

    app = _make_bare_app(root, db)
    app._own_key = crypto.generate_private_key()
    app._lamport_clock = 0
    app._network = None

    class FakeExpenseDialog:
        def __init__(self, parent, users, own_pubkey, currency, rates):
            self.result = {
                "description": "Dinner",
                "amount": 1250,
                "payer_key": "alice",
                "category": "Food & Drink",
                "expense_date": None,
                "new_attachment": {
                    "sha256": crypto.hash_bytes(b"receipt bytes"),
                    "filename": "receipt.png",
                    "size": 13,
                    "mime": "image/png",
                },
                "existing_attachment": None,
                "original_amount": None,
                "original_currency": None,
                "debtor_keys": ["alice"],
                "split_mode": "equal",
                "split_percentages": None,
                "split_custom_amounts": None,
            }

    storage.save_attachment_file(b"receipt bytes", crypto.hash_bytes(b"receipt bytes"))

    with patch("gui.ExpenseDialog", FakeExpenseDialog), patch("gui.mb.showwarning"):
        app._add_expense()

    expenses = app._load_expenses()
    assert len(expenses) == 1
    exp = expenses[0]
    assert exp.attachment is not None
    assert exp.attachment.filename == "receipt.png"
    assert exp.attachment.is_stored == 1
    assert exp.attachment.signature  # was signed

    app._refresh()
    assert len(app._event_list.winfo_children()) > 0
